# begin token definitions

WHITESPACE = /\s+/;
COMMENT = /#[^\r\n]*$/;
EOL = /\r|\n|\r\n/;
IDENTIFIER = /[-_a-zA-Z][-_a-zA-Z0-9]*(?:\([0-9]+\))?/;
NUMBER = /[0-9]+(?:\.[0-9]+)?(?:ns\b)?/;
HEADER = "@header";
CONFIG = "@config";
COMMA = ",";
COLON = ":";
EQUAL = "=";
STRING = /"[^"\r\n]*"/;
MULTILINE_STRING = /<<.*?>>/;
LCURLY = "{";
RCURLY = "}";

# begin grammar
Program
	:	BoardDefinitions
	;

BoardDefinitions
	: Boards
	;

Boards
	: Boards Board
	| Board
	;

Board
	: Names LCURLY Buses RCURLY
	| Names COLON Name LCURLY Buses RCURLY;
	;

Buses
	: Buses Bus
	| Bus
	;

Bus
	: Name COLON FpgaPins
	;

FpgaPins
	: FpgaPins COMMA FpgaPin
	| FpgaPin
	;

FpgaPin
	: Name
	| Name LCURLY Names RCURLY
	;

Names
	: Names COMMA Name
	| Name
	;

Name
	: IDENTIFIER
	| STRING
	;
